# Generated by Django 3.0.5 on 2020-04-20 07:34

import core.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/listing/', location='/Users/yananw/Desktop/MarketPlace/server/marketplace/media/listing/'), upload_to=core.models.image_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=126, size=6)),
                ('description', models.TextField()),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Listing')),
            ],
        ),
    ]
