# Generated by Django 3.0.5 on 2020-04-22 21:49

import core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/listing/', location='/home/benjamin/Documents/MarketPlace/server/marketplace/media/listing/'), upload_to=core.models.image_directory_path),
        ),
    ]
