# Generated by Django 3.0.5 on 2020-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0001_initial'),
        ('chat', '0002_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
